# Generated by Django 5.2.11 on 2026-02-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_idempotency_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status_8e5503_idx',
            old_name='tasks_task_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_task_ty_265be9_idx',
            old_name='tasks_task_task_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_priorit_139b4b_idx',
            old_name='tasks_task_priority_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='tasks_webho_task_id_3e4663_idx',
            old_name='tasks_webhookdelivery_task_event_queued_at_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='tasks_webho_status_9e7993_idx',
            old_name='tasks_webhookdelivery_status_queued_at_idx',
        ),
    ]
